pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                parallel (
                    a: {
                        echo "This is branch a"
                    },
                    b: {
                        echo "This is branch b"
                    }
                )
            }
        }
        stage('Test') {
            steps {
                echo "Hello from Test2"
            }
        }
        stage('Deploy') {
            steps {
                echo "Hello from Deploy"
            }
        }
    }
}